### ISSUE TITLE
Implement Social Card Preview

### ISSUE THREAD

**Issue by iAbhinav** [Dominate-X-Club/Copod#13]
Display Social Preview, when [copod.space](https://copod.space) link is pasted in a social media app.

To be tested on

- [x] Twitter
- [x] iMessage
- [x] Whatsapp
- [x] Facebook
- [x] Instagram DM

<img width="602" alt="Screenshot 2024-05-23 at 3 38 23 PM" src="https://github.com/Dominate-X-Club/Copod/assets/6393661/c78ec6d9-1b08-455d-bcff-6d835a1d79ac">

**Comment by code-withAshish** [comment]
i think the twitter preview also started working recently @iAbhinav , so i consider this issue resolved and closing this.
