### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by iAbhinav** [Dominate-X-Club/Copod#2]
From the landing page, user is directed to the Login Page.

Use Supabase Auth with email and next-middleware to guard authenticated routes

Login page should also have privacy policy and terms of use components. 

Sign up, Sign in and Logout with email

**Comment by iAbhinav** [comment]
> can I use Prisma?
> 
> 

@code-withAshish can we?

**Comment by code-withAshish** [comment]
> > can I use Prisma?
> > 
> > 
> 
> @code-withAshish can we?

Technically you can , because prisma supports postgresql and supabase provides basically a postgres instance only but in my opinion I won't recommend it as we don't have the need for it, supabase-js library handles it very well.

**Comment by lakshya-roonwal** [comment]
### Can We Create Something like this
![image](https://github.com/Dominate-X-Club/Copod/assets/76898541/698f2823-0536-46a8-a070-06c0dfc5274e)

**Comment by QQ07** [comment]
Frontend doesn't matter at this point bro.. functionality matters.. as we would have to redesign based on the landing page's theme..

**Comment by iAbhinav** [comment]
> Frontend doesn't matter at this point bro.. functionality matters.. as we would have to redesign based on the landing page's theme..

Yes, i first want to finalize landing page, and use that theme on other pages and components

**Comment by anshul45** [comment]
@iAbhinav as landing page not finalize yet. Can I implement the log in with email functionality here as it created already :  [login page](https://github.com/Dominate-X-Club/Copod/blob/main/src/app/auth/login/action.ts) ? For signup, can I create register routes like [auth/register](https://github.com/Dominate-X-Club/Copod/tree/main/src/app/auth) here? And  middleware for protecting our future components or pages

**Comment by iAbhinav** [comment]
Yes go on please 🚀

**Comment by code-withAshish** [comment]
as @lakshya-roonwal pr has already been merged, this issue also stands resolved and will be closed.
